[config]
reload_apps = true

[config.reload_apps_list]
kitty = true
gtk_theme = true

[config.wallpaper]
command = "swww"
arguments = [
  "img",
  "-t",
  "outer",
  "--transition-duration",
  "1.5",
  "--transition-step",
  "255",
  "--transition-fps",
  "60",
  "-f",
  "Nearest",
]
set = true

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar-colors.css"
output_path = "~/.config/waybar/maincolors.css"
post_hook = "pkill -SIGRTMIN+8 waybar"

[templates.eww]
input_path = "~/.config/matugen/templates/eww.scss"
output_path = "~/.config/eww-which-key/eww.scss"

[templates.dwm]
input_path = "~/.config/matugen/templates/dwm.h"
output_path = "~/.config/dwm/colors.h"

[templates.dwmbar]
input_path = "~/.config/matugen/templates/dwmbar.sh"
output_path = "~/.local/bin/statusbar/themes/colors.sh"
post_hook = "pidof dwmbar-colored || pkill dwmbar-colored || ~/.local/bin/dwmbar-colored &"

[templates.waybar-insert]
input_path = "~/.config/matugen/templates/waybar-insert.css"
output_path = "~/.config/waybar/MODES/colors-Insert-Mode.css"
post_hook = "pkill -SIGRTMIN+8 waybar"

[templates.waybar-run]
input_path = "~/.config/matugen/templates/waybar-run.css"
output_path = "~/.config/waybar/MODES/colors-Run-Mode.css"
post_hook = "pkill -SIGRTMIN+8 waybar"

[templates.waybar-normal]
input_path = "~/.config/matugen/templates/waybar-normal.css"
output_path = "~/.config/waybar/MODES/colors-Normal-Mode.css"
post_hook = "pkill -SIGRTMIN+8 waybar"

[templates.cava]
input_path = "~/.config/matugen/templates/wallpaperCavaConfig.toml"
output_path = "~/.clones/wallpaper-cava/config.toml"
post_hook = "pidof wallpaper-cava && killall -SIGUSR1 wallpaper-cava && uwsm app -- ~/.clones/wallpaper-cava/target/release/wallpaper-cava &"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/hypr/source/colors.conf"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.config/kitty/colors.conf"
post_hook = "killall -SIGUSR1 kitty &"

[templates.gtk3]
input_path = "~/.config/matugen/templates/colors.css"
output_path = "~/.config/gtk-3.0/colors.css"

[templates.gtk4]
input_path = "~/.config/matugen/templates/colors.css"
output_path = "~/.config/gtk-4.0/colors.css"

[templates.nvim2]
input_path = "~/.config/matugen/templates/colors-wal.vim"
output_path = "~/.cache/wal/colors-wal.vim"

[templates.nvim]
input_path = "~/.config/nvim/pywal/matugen.lua"
output_path = "~/.cache/wal/base46-dark.lua"

[templates.pywaljson]
input_path = "~/.config/matugen/templates/pywal-colors.json"
output_path = "~/.cache/wal/colors.json"
post_hook = "pywalfox update &"

[templates.colors]
input_path = "~/.config/matugen/templates/colors"
output_path = "~/.cache/wal/colors"
post_hook = "sh ~/.clones/pywal-obsidianmd/pywal-obsidianmd.sh /home/kvl/myVault &"

[templates.pywalsh]
input_path = "~/.config/matugen/templates/colors.sh"
output_path = "~/.cache/wal/colors.sh"
post_hook = "walogram -B > /dev/null 2>&1 &"

[templates.pywalwalfile]
input_path = "~/.config/matugen/templates/wal"
output_path = "~/.cache/wal/wal"

[templates.rofi]
input_path = "~/.config/matugen/templates/colors.rofi"
output_path = "~/.config/rofi/colors/colors.rasi"

[templates.zathura]
input_path = "~/.config/matugen/templates/colors-zathura"
output_path = "~/.config/zathura/zathurarc"

[templates.yazi]
input_path = "~/.config/matugen/templates/colors-yazi.toml"
output_path = "~/.config/yazi/theme.toml"

[templates.hyprfabrictor]
input_path = "~/.config/Ax-Shell/config/matugen/templates/ax-shell.css"
output_path = "~/.config/hyprfabricated/styles/colors.css"
post_hook = "fabric-cli exec ax-shell 'app.set_css()' &"

[templates.ax-shell]
input_path = "~/.config/Ax-Shell/config/matugen/templates/ax-shell.css"
output_path = "~/.config/Ax-Shell/styles/colors.css"
post_hook = "fabric-cli exec ax-shell 'app.set_css()' &"

[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true
